apiVersion: v1
kind: Service
metadata:
  name: { { .Values.api.name } }
spec:
  selector:
    app: { { .Values.api.name } }
  ports:
    - protocol: TCP
      port: 80
      targetPort: { { .Values.api.port } }
